env = createEnvironment()
proc = env.createProc("testproc")
proc.nop()
proc.nop()
proc.label("testpoint")
proc.move(0, 0x1234)
proc.jump("pastpoint")
proc.move(1, 0xAA)
proc.move(2, 0xBB)
proc.label("pastpoint")
proc.move(3, 0xCC)
